require:
  - rubocop-rspec
  - rubocop-factory_bot

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 100

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

FactoryBot/CreateList:
  Enabled: true

FactoryBot/FactoryClassName:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false
